### ISSUE TITLE
detector not convergence

### ISSUE THREAD

**Issue by zebin-dm** [The-Learning-And-Vision-Atelier-LAVA/PoSFeat#3]
The detector loss is very large , and seem not convergence?
![image](https://user-images.githubusercontent.com/94420096/172040166-1193eb1e-41ae-473f-9a80-b27a2fef5c6d.png)

**Comment by KunB-Fighting** [comment]
For the detector, we can not judge convergence with the loss. Because we sample the points according to the score map randomly, which makes the points not stable during training, the loss can fluctuate dramatically. Additionally, we use sum instead of mean in kploss, which makes the value of loss varies over a wide range.

You should visualize the score map of keypoint to judge convergence, and we have provided tools in this repo. Empirically, the detector will converge in 1000-5000 batches (it is up to the batch size, and takes about 1-2 hours).
